---
- name: install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add apt-key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
    - name: Add MongoDB repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    - name: install MongoDB
      apt:
        name: mongodb-org
    - name: enable MongoDB
      systemd:
        name: mongod
        enabled: yes
